### ISSUE TITLE
Query escapes SQL too aggressively

### ISSUE THREAD

**Issue by ljocha** [RECETOX/galaxytools#101]
When running with trivial SQL query like:

select * from r where rtp > 0

I get:

pandasql.sqldf.PandaSQLException: (sqlite3.OperationalError) near "__gt__": syntax error
[SQL: select * from r where rtp __gt__ 0]

IMHO this is due to some aggressive escaping, probably at Galaxy side, which replaces "dangerous" characters like >. 

It should be either disabled or unescaped in the python script.

**Comment by xtracko** [comment]
The Galaxy documentation says almost nothing about escaping characters. Though, the escaping may be caused by the following line: https://github.com/RECETOX/galaxytools/blob/683f472a44f296d65cf572a5e720839fc4c0141e/tools/query/query.xml#L60

The generated config file from a sample dummy invocation is:
```JSON
{"tables": [], "query": "sel __gt__ a", "result": {"path": "/mnt/volume/shared/ces-nya/nfs4/home/umsa/object_store_cache/021/dataset_21375.dat", "name": null, "format": "csv"}}
```
meaning that some escaping between python and galaxy are happening.

**Comment by xtrojak** [comment]
This can be achieved by adding 

```<options sanitize="False"/>```

to the tool wrapper ([example](https://github.com/sybila/eBCSgen/blob/cf50c2c5fedd13570abe574bec79706ca93b3fcc/config/eBCSgen_PCTLmodelChecking.xml#L3)) or probably applying [param sanitized](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-param-sanitizer) for a particular parameter.

**Comment by martenson** [comment]
If we prevent sanitization for SQL no sane admin will ever install this tool on any Galaxy unless the instance is locked down and private and even then they will possibly have nightmares through the night.

I understand it is tempting to "just send SQL" and be done with it but tool like that cannot be hosted safely.

**Comment by hechth** [comment]
The state of the tool is overall questionable so I just wouldn't work on it at the moment.
