### ISSUE TITLE
Zenodo Authors

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#103]
I had a look at the Zenodo DOI and noticed that I'm listed as hechth - which is somewhat not my real, full name (though sounds very charming!) :D

Would it be possible to change that somehow?

**Comment by martenson** [comment]
I think it is based on your Github name, yours is the same as usernam:`hechth`.

**Comment by hechth** [comment]
I see - didn't know GitHub also has a 2 name system.
