### ISSUE TITLE
aplcms: Implement aplcms IO functionality inside R wrapper

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#111]
Since r-hdf5r will be removed from apLCMS (see [here](https://github.com/RECETOX/apLCMS/issues/11)), the [storing functionality](https://github.com/RECETOX/apLCMS/blob/09896e5e27f86c2bb22264eca5290b0180048146/apLCMS/R/io.R#L27) should be moved to a wrapper script connected to the galaxy tool.

**Comment by martenson** [comment]
implemented at https://github.com/RECETOX/galaxytools/pull/133/files#diff-27540fba2918e2c0efe605e97f7e636b8b229c1f8e385c4b6c85eb4ba24ea0b9R1
