### ISSUE TITLE
Change MatchMS CSV output identifier column

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#120]
The first column - containing the reference compound identifier - currently contains the name, which can contain commas, therefore disturbing the csv structure. The name could instead be appended as last column and the first column could be the chemical formula, which doesn't contain commas.

**Comment by martenson** [comment]
even if we append it as last column it will be weird csv (different number of columns per row) - we can e.g. escape it maybe

**Comment by hechth** [comment]
I think we agreed that actually switching it to `tsv` format is going to be the best, in order to avoid this issue.

**Comment by hechth** [comment]
This issue has been merged with #119
