### ISSUE TITLE
waveica:Fix typo in categories to actually have the correct category

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#136]
https://github.com/RECETOX/galaxytools/blob/636146595a7067d7062961dbfa834f366c342156/tools/waveica/.shed.yml#L7

Only lowercase 'categories' will be recognized.

**Comment by martenson** [comment]
Are you sure this is the case? I cannot imagine why we would differentiate based on case, that would be a bug on the side of planemo/toolshed I think.
