### ISSUE TITLE
Add creator tag to all galaxy tool wrappers

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#137]
For an example see https://github.com/mvdbeek/galaxy/blob/9952be7a80ea11fc5f95c90b337b1b31b73bc29f/test/functional/tools/mulled_example_multi_1.xml#L6-L15

The creator for each tool should be the person creating the wrapper, as an organization we should also add RECETOX.

Tools:
- [ ] matchms
- [ ] recetox_aplcms_unsupervised
- [ ] waveica
- [ ] ramclustr_csv
- [ ] ramclustr_xcms
- [ ] recetox_xmsannotator_simple
- [ ] filter_compounds
- [ ] biotransformer

**Comment by martenson** [comment]
Looks useful. One note: the `<creator>` tag does not seem to be officially part of the [tool schema](https://docs.galaxyproject.org/en/master/dev/schema.html) so this enhancement seems to be very future-facing.

**Comment by hechth** [comment]
It is already present in the schema: https://github.com/mvdbeek/galaxy/blob/9952be7a80ea11fc5f95c90b337b1b31b73bc29f/lib/galaxy/tool_util/xsd/galaxy.xsd#L516

Thanks to Marius Van Den Beek for pointing this out :)

**Comment by martenson** [comment]
Alright, should be part of the schema after https://github.com/galaxyproject/galaxy/pull/12242 is merged. Now it looks like even better idea than before! :)
