### ISSUE TITLE
matchms: Add option to output only the best matches for spectra

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#159]
Make option to only output one csv with the following layout

| query | reference | score | matches |
|-------|------------|--------|----------|
| C001 | Acetochlor | 0.87 | 10|
| C002 | Nicotine | 0.43 | 5 |

**Comment by ElliottJP** [comment]
Also, option to only output matches above certain score.

**Comment by hechth** [comment]
That would change the layout to something like this? Or should we add additional columns? I think the layout below would be easiest, since it allows sorting for compound and then score.

| query | reference | score | matches |
|-------|------------|--------|----------|
| C001 | Acetochlor | 0.87 | 10|
| C001 | Benzene | 0.79 | 9 |
| C002 | Nicotine | 0.43 | 5 |
