### ISSUE TITLE
aplcms: Implement two-step-hybrid version of the tool

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#174]
Add a wrapper that uses the two-step-hybrid method as described in this paper https://doi.org/10.1038/s41598-020-70850-0 after implementing RECETOX/recetox-aplcms#23

The code is already available: https://github.com/RECETOX/recetox-aplcms/blob/master/R/two.step.hybrid.R

**Comment by maximskorik** [comment]
Implemented in #264
