### ISSUE TITLE
matchms: Extract filtering into specific tool

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#189]
The matchms filter modules should be extracted into an individual tool with the following filters:

- [ ] Normalize intensities
- [ ] Apply default filters
- [ ] Filter relative intensity
- [ ] Filter m/z range
- [ ] Clean metadata -> appluy all "add" and cleaning filters if possible, so that the spectra have canonical metadata

The galaxy tool could work in such a way that it allows iteratively adding of steps in the filtering and the tool just works through these steps, or to always only perform a single step, which will on the other hand result in very long pipelines.

**Comment by hechth** [comment]
I don't think a filter will be run multiple times, but I'm not sure if implementing a tool which will run multiple filters is not more cumbersome than having one tool which can run all filters but only one at a time and then chaining the filters into a workflow in galaxy. @martenson  what would be your take on this?

**Comment by martenson** [comment]
Even if the order of filter application is important we can implement this as one tool that can apply any combination of filters. The UX can be similar to that of MSME when calling services in order. Invoking the same tool in series seems less efficient and I am not clear on what the benefits would be.

**Comment by xtrojak** [comment]
Actually, a more straightforward approach I tried is using a series of conditionals. Have a look in the respective PR #207.
