### ISSUE TITLE
MSMetaEnhancer: Dynamic conversion options

### ISSUE THREAD

**Issue by xtrojak** [RECETOX/galaxytools#197]
It would be useful to generate all possible conversion options dynamically using a [function](https://github.com/RECETOX/MSMetaEnhancer/pull/55) from `MSMetaEnhancer`. That way, adding/changing services and conversions will not influence the Galaxy tool.

**Comment by xtrojak** [comment]
To achieve that, a deprecated [`code` tag](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-code) could be potentially used if its still supported. Here is example how to use it:

- add to tool's config `.xml`: 

```xml
...
<code file="wrapper.py" />

<inputs>
    ...
    <param name="jobs" type="select" optional="true" multiple="true" label="Available jobs" dynamic_options="get_jobs()"/>
</inputs>
```

- add to `wrapper.py`:

```python
def get_jobs():
    # artificial example how to pass dynamic data to galaxy tool config
    # (label, what-is-passed-as-arg, is-check-by-default)
    return [("PubChem: inchi -> name", "('PubChem', 'inchi', 'name')", False),
            ("CTS: formula -> name", "('CTS', 'formula', 'name')", False)]
```

> ! Note that running the tool with this will lead to an import error because the script `wrapper.py` is exposed before the environment with required packages is activated (thus deprecated).

**Comment by hechth** [comment]
Then I assume creating them dynamically is just not an option @martenson ?

**Comment by xtrojak** [comment]
What seems to be working is to take the list of [options from a file](https://docs.galaxyproject.org/en/master/dev/schema.html#tool-inputs-param-options), but it has to be already existing. Such a file can be part of the repository, but it had to be always up to date (maybe a CI could ensure that?).

**Comment by martenson** [comment]
I would avoid the deprecated `<code>` tag and set up a CI to keep an up to date options file as @xtrojak suggested.

**Comment by xtrojak** [comment]
I have enumerated the options in `macro` file, which seems to be the easiest approach. However, I'm not sure about the CI which will make sure that the options are up to date - do we want to set it up in this repository? The function which generates the options could be part of the wrapper or possibly also part of the `MSMetaEnhancer` tool (although it's used only in context of Galaxy). What do you think @martenson?

**Comment by martenson** [comment]
As discussed out of band yesterday the current approach will likely be to generate the options as a part of MSMetaEnhancer release process and store it in its repo. With every Galaxy wrapper being updated to the new MSME version the `macros.xml` file needs to be updated to reflect any changes in the options. 

Both of these processes should be captured in their respective readmes.
