### ISSUE TITLE
MSMetaEnhancer: matchms allows export to non-MSP files

### ISSUE THREAD

**Issue by xtrojak** [RECETOX/galaxytools#200]
As indicated in [this](https://github.com/matchms/matchms/issues/274) issue, `matchms` required to the filename extension to be `.msp` when exporting mass spectra data in this format. In this [PR](#276), this requirement was removed. Once a new bioconda package version is released (`> 0.10.0`), a temporary `.msp` file does not have to be created anymore and a `.dat` file can be used directly in the wrapper.

**Comment by xtrojak** [comment]
This feature was included in matchms [0.11.0](https://github.com/matchms/matchms/releases/tag/0.11.0).

**Comment by xtrojak** [comment]
The feature seems to be working fine, but `matchms` prints to stdout the following message:
 `YYYY-MM-DD HH:MM:SS:WARNING:matchms:save_as_msp:Spectra will be stored as msp file with extension .dat`

**Comment by hechth** [comment]
I think this is legit to have a warning.
