### ISSUE TITLE
remove october_recetox_xmsannotator

### ISSUE THREAD

**Issue by martenson** [RECETOX/galaxytools#209]
and merge the needed functionality (if any) to the main tool

**Comment by hechth** [comment]
It should only be removed after merging the actual functionality and having a tool which actually provides the same.

**Comment by martenson** [comment]
@hechth hence this issue. The prototype tool cannot be hosted long-term publicly (and has already been uninstalled form umsa) since it has unsafe parameter handling.

**Comment by hechth** [comment]
@xtrojak where are we on this? The tools are still in the repo but no longer available from the toolshed?

**Comment by xtrojak** [comment]
With merge of #367 it will be removed from the repo. After that, I will uninstall them from UMSA and deprecate in the toolshed.
