### ISSUE TITLE
Create tool which creates a 3D PCA plot for WaveICA output (sample metadata + intensities) with plotly

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#239]

**Comment by xtrojak** [comment]
There are multiple attributes in the data, which can be shown in the plot: `sampleName`, `class`, `sampleType`, `injectionOrder`, `batch`. I would definitely include `sampleName` to be able to identify a particular data point. What about others? 

One of `class`, `sampleType` or `batch` can also be used to assign a colour to data points. @hechth you suggested to use `sampleType`, maybe `batch` is also a good candidate?

**Comment by hechth** [comment]
There are multiple options here which would be possible and make sense:

1. Ask the user to provide (i) the index where the feature columns to use for the PCA start and (ii) the name of the column to use for the color, then show all non-feature columns in the hover.
2. Create a fixed set of metadata columns which are shown in the hover and ask the user only for color using a selector. All other columns are treated as intensity and are used for the PCA.
3. always use the class for coloring and have a fixed metadata column.
4. Create an option similar to MSME where the user can add metadata columns and then pass the name of the color column as individual parameter. Everything else is considered feature columns.

@xtrojak @martenson I personally think solution 1 and 4 are maybe the best ones, followed by 2. The documentation simply has to include the columns which are considered for metadata. Otherwise we also have extensive user input... but I'm open for discussion.

I can also try to get some input from the lab group what they would prefer, but we shouldn't make it to complicated - so maybe option 2 is the best in that sense.

**Comment by xtrojak** [comment]
I also had short discussion with @martenson whether to implement this as a Galaxy tool or proper Galaxy visualisation, I suppose if we want to add some of these options for the user, the second option would not be possible anymore?

**Comment by hechth** [comment]
I think having it as a tool first instead of built-in visualization might be easier to begin with and we can parameterize it.
We can likely still reuse the code if we want to make it a built-in visualization afterwards

**Comment by martenson** [comment]
How novel is this 3D PCA plot going to be? Can we reuse some npm package to deliver the interactive visualization in the browser? 

The typical tradeoffs are that if you run it as a tool, it won't be interactive and if you run it in browser, you'll have trouble handling very large data.

**Comment by martenson** [comment]
If something like https://plotly.com/python/3d-scatter-plots/ is what we need then making a tool that runs it makes sense. However we cannot run python in the browser though, so if we later want to make it integrated visualization we'll need to switch to JS. So a call has to be made.

**Comment by xtrojak** [comment]
Implemented using JS Plotly, PR is [here](https://github.com/galaxyproject/galaxy/pull/13771).

**Comment by xtrojak** [comment]
The visualization is already merger, needs to be tested in production.

**Comment by martenson** [comment]
It is deployed on umsa, ready for more testing.

**Comment by hechth** [comment]
I think this can be closed?

**Comment by martenson** [comment]
I think so. The performance should get own issue.
