### ISSUE TITLE
is there a feasible default for retip filter's tolerance param?

### ISSUE THREAD

**Issue by martenson** [RECETOX/galaxytools#24]
The [param](https://github.com/RECETOX/galaxytools/blob/master/tools/retip/retip_filter_rt.xml#L12) is required in the wrapper but unspecified by default. Can we supply a reasonable default?

cc @ljocha

**Comment by ljocha** [comment]
Good question. Frankly, I barely know before we run it through some real data. I'd suggest to start with something quite tolerant, e.g. 30 %,  and we can tighten the default later.

**Comment by smartx-usman** [comment]
I already see a new PR from you in [Retip](https://github.com/RECETOX/Retip/pull/7). In accordance with the changes to that PR, I will add 30% as a default.
