### ISSUE TITLE
create a tool for previewing (our) H5 

### ISSUE THREAD

**Issue by martenson** [RECETOX/galaxytools#27]
Something human readable like csv, yml, json etc.

**Comment by hechth** [comment]
Have a look at https://docs.h5py.org/en/stable/

**Comment by xtracko** [comment]
I suggest using Pandas, it has `read_hdf` function and its straightforward
to use. As soon as we will have free capacity we should implement it.

**Comment by hechth** [comment]
I guess this can be marked as deprecated?

**Comment by xtracko** [comment]
Oh, thanks. I didn't found this issue when I was submitting #63. Solved #63 

Today, I talked to @maximskorik and the converter between apLCMS and RAMclutr (issue #51) seems to be still relevant.
