### ISSUE TITLE
matchms similarity: Add Spec2Vec module

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#277]
Using Spec2Vec as a similarity metric by accepting a trained model as an additional parameter would be a cool feature!

For the procedure see [here](https://github.com/RECETOX/galaxytools/issues/276).

Relevant papers:
http://dx.doi.org/10.1371/journal.pcbi.1008724

Steps:
- [x] Train the model on provided testing data
- [ ] Include in matchms similarity wrapper
- [x] #315
- [ ] #316

Problems:
- [x] #290

**Comment by maximskorik** [comment]
Adding a diagram from #290 to have a perspective of the proposed Spec2Vec workflow.

![diagram](https://user-images.githubusercontent.com/12066490/181482101-93132083-80d7-4c45-b4ec-40a83e8c7090.png)
