### ISSUE TITLE
aplcms-recover-weaker: failure with parallelism for larger input

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#279]
See the bug report in this history: https://umsa.cerit-sc.cz/u/hechth/h/20220615-seminal-plasma-full-study-new-ramclustr

**Comment by hechth** [comment]
This might be related to the small nodes -> this has to be adjusted in the Galaxy destinations

**Comment by xtrojak** [comment]
[Changing](https://gitlab.ics.muni.cz/recetox/mass-spectrometry/umsa-galaxy/-/merge_requests/19) `recetox_aplcms_recover_weaker_signals` tool to destination `dest_huge` (32 cores) did not resolve the issue.

https://umsa.cerit-sc.cz/u/xtrojak/h/imported-20220615-seminal-plasma-full-study-new-ramclustr

**Comment by hechth** [comment]
This is still happening with a different error: https://umsa.cerit-sc.cz/u/hechth/h/20230224-recetox-aplcms-unsupervised-full-dilution-series

**Comment by hechth** [comment]
@zargham-ahmad I think you actually fixed this, right? The problem was with the sample names being subsets of another and then then 2 tables being concatenated if I am not mistaken?

**Comment by zargham-ahmad** [comment]
@hechth Yes, it was fixed in this [PR ](https://github.com/RECETOX/recetox-aplcms/pull/180)
