### ISSUE TITLE
recetox-aplcms: Create `suite` similar to `xcms` in shed

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#282]
`xcms` can be installed as a suite containing all tools for the individual steps - this would also make installation easier. This should then have a dependency on all the other actual tools.

**Comment by xtrojak** [comment]
I don't think there is such thing. 

However, what I have found is that you can generate a `tool_list` from workflow `.ga` files and use `planemo` to install tools from the list. So once we create proper [workflows](https://github.com/RECETOX/workflow-testing/pull/14), any admin can easily obtain and install required tools on their Galaxy instance. [Here](https://artbio.github.io/GalaxyKickStart/installing_tools_and_workflows/) are some details.

**Comment by bgruening** [comment]
What you are searching is https://ephemeris.readthedocs.io/en/latest/commands/workflow-install.html

Do not use suites, they are deprecated and not good. 

Also consider creating YML files like: https://github.com/usegalaxy-eu/usegalaxy-eu-tools those can be installed with ephemeris as well. If you like add such YML files to this repo and they get installed on the EU server automatically :)

**Comment by hechth** [comment]
@bgruening thanks so uch for the hints! Basically the yaml file will point to the tool in the toolshed and will then automatically install it on usegalaxy.eu if I understand it correctly?

I'll check out the workflow install!

**Comment by bgruening** [comment]
Yes - and of course, you can use the same mechanism, repo for your instance.
