### ISSUE TITLE
matchms: Custom GENSIM exporter for Spec2Vec trained model since pickle is not very safe

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#290]
![Image](https://user-images.githubusercontent.com/12066490/181482101-93132083-80d7-4c45-b4ec-40a83e8c7090.png)

**Comment by hechth** [comment]
xref https://github.com/iomega/spec2vec/issues/78

**Comment by maximskorik** [comment]
xref https://github.com/iomega/spec2vec/pull/80
