### ISSUE TITLE
recetox-aplcms-extract-features input form

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#291]
- [x] `sigma_ratio_lim_min` & `sigma_ratio_lim_max` should be conditional on bi-Gaussian peak shape
- [x] ~~`moment_power` is likely only applicable if estimation mode is moment~~
- [ ] explain `BIC_factor` better
- [x] ~~`make `baseline_correct_noise_percentile` only appear if the `baseline_correct` is NA`~~
- [ ] explain bandwidth parameters better
- [ ] explain `sd_cut_min` and `sd_cut_max` parameters better

**Comment by xtrojak** [comment]
Actually `baseline_correct_noise_percentile` is used only in plotting of histograms, so we can remove it.
