### ISSUE TITLE
Create a tool to create a fragment library from an MSP, with output format similar to PeakPantheR, AssayR etc. -> example file is available.

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#294]
@ElliottJP: Do we have an example file?

**Comment by maximskorik** [comment]
I updated what seemed to be a wrong GitHub handle in the issue description.

**Comment by hechth** [comment]
possible overlap with #423

**Comment by hechth** [comment]
See PeakPantheR format here: https://phenomecentre.github.io/peakPantheR.github.io/index.html
