### ISSUE TITLE
RI filtering in galaxy's MatchMS version not working

### ISSUE THREAD

**Issue by michal-stary** [RECETOX/galaxytools#298]
The RI filtering is not working. In the relative [test](https://github.com/RECETOX/galaxytools/blob/ca44513d50b29a4706e2a2db96c23ef6688b7c2d/tools/matchms/matchms_similarity.xml#L132) the value of RI tolerance set to 60. But in the output [match file](https://github.com/RECETOX/galaxytools/blob/master/tools/matchms/test-data/similarity/matches_test6_out.tsv) or [scores file](https://github.com/RECETOX/galaxytools/blame/master/tools/matchms/test-data/similarity/scores_test6_out.tsv), the first compound (Perylene_2H12) is matched with 5 peaks to C19 spectrum (the last column). 

This should not happen as RI value of C19 in the [input file](https://github.com/RECETOX/galaxytools/blob/master/tools/matchms/test-data/similarity/fill2.msp)  is **4135.446429**. And the RI of Perylene_2H12 in the [library file](https://raw.githubusercontent.com/RECETOX/galaxytools/master/tools/matchms/test-data/similarity/recetox_gc-ei_ms_20201028.msp) is **2876**. 

Overall, despite specifying the RI in the GUI and program going through the related [if statement](https://github.com/RECETOX/galaxytools/blob/ca44513d50b29a4706e2a2db96c23ef6688b7c2d/tools/matchms/matchms_similarity_wrapper.py#L82). (The succeeding print is printing), the output data are not filtered.

**Comment by maximskorik** [comment]
@michal-stary thanks for the detailed explanation!

@xtrojak could you please update the wrapper on UMSA?

**Comment by xtrojak** [comment]
@maximskorik matchms similarity version `0.15.0+galaxy1` is installed on UMSA.

**Comment by hechth** [comment]
@michal-stary please check if this works now

**Comment by michal-stary** [comment]
@hechth yes, it works
