### ISSUE TITLE
Check CI action R linting

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#307]
@xtrojak seems like something is wrong within the CI and some R linting action is no more available.

_Originally posted by @hechth in https://github.com/RECETOX/galaxytools/issues/306#issuecomment-1290348332_

**Comment by bgruening** [comment]
This is fixed on IUC already, simply copy the latest CI integration from https://github.com/galaxyproject/tools-iuc/tree/master/.github/workflows

**Comment by xtrojak** [comment]
Great idea Björn, did exactly that in #309. Thanks!
