### ISSUE TITLE
apLCMS: update wrappers to `v0.10.0`

### ISSUE THREAD

**Issue by xtrojak** [RECETOX/galaxytools#308]
With the new release `v0.10.0` of `apLCMS`, the wrappers need to get updated. Most of them will be completely replaced.

Wrappers that need to be introduced:

- [ ] `remove_noise` - call `proc.cdf`
- [ ] `generate_feature_table` - call `prof.to.features`
- [ ] `compute_clusters`
- [ ] `compute_template`
- [ ] `correct_time`
- [ ] `merge_known_table` - call `merge_features_and_known_table`

Wrappers to be changed:

- [ ] `align_features` - call `create_aligned_feature_table` instead of `align_features`
- [ ] `recover_weaker_signals` - executed in parallel per corrected features table

Obsolete wrappers:

- [ ] `adjust_time`
- [ ] `extract_features`
- [ ] `hybrid`
- [ ] `unsupervised`
- [ ] `two_step_hybrid`

The amount of code in `utils.R` and `main.R` should also be significantly reduced. Wrappers for `unsupervised` and `hybrid` are obsolete because they can be replaced by workflows. Special attention needs to be paid to the outputs of the workflows, as it is not only output of the last step.

**Comment by hechth** [comment]
This diagram also shows the newly planned workflow: 
![image](https://user-images.githubusercontent.com/12066490/199191902-a9037079-dc00-4aae-862c-5ded8f0fbe10.png)

**Comment by hechth** [comment]
@xtrojak I agree with the names for the newly introduced wrappers as well as with the obsolete wrappers.

I think the unsupervised and hybrid should be then distributed and described as workflows or used within the package.
One thing we then have to consider in case of the workflow is maybe how we can re-use parameters or so? Not sure about that.

It would just be good to keep the overall parameterization of the package as simple as possible. But this is maybe also something that we can address after merging https://github.com/RECETOX/recetox-aplcms/pull/154.

**Comment by maximskorik** [comment]
> Wrappers with questionable future:
 two_step_hybrid

I believe this can be moved to obsolete too. This whole wrapper should, in theory, just reuse all the steps that we wrapped for `hybrid.R`. Maybe with a few adjustments.

**Comment by hechth** [comment]
@maximskorik I agree. For now it should be marked as obsolete and then we will have maybe one or two new tools and the two step hybrid as a new workflow.

**Comment by xtrojak** [comment]
Alright, thanks for the comments, I updated the description accordingly. The wrapper `two_step_hybrid` will be also removed from the repo and consequently marked as obsolete in the toolshed.

**Comment by hechth** [comment]
@yguitton this graphic shows the new layout of steps that I mentioned, resulting in slightly different workflows made up from similar components.
