### ISSUE TITLE
Update GitHub workflows

### ISSUE THREAD

**Issue by xtrojak** [RECETOX/galaxytools#310]
- [ ] [deprecated Node12](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) (deadline Summer 2023)
- [ ] [deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) `save-state` and `save-output` (deadline 31st May 2023)

**Comment by xtrojak** [comment]
We can use the latest CI integration from IUC https://github.com/galaxyproject/tools-iuc/tree/master/.github/workflows

**Comment by hechth** [comment]
@xtrojak does this mean that the sub tasks are resolved?

**Comment by xtrojak** [comment]
@hechth yes, everything should be good now.
