### ISSUE TITLE
msmetaenhancer: tool finishes with error

### ISSUE THREAD

**Issue by maximskorik** [RECETOX/galaxytools#312]
MSMetaEnhancer wrapper runs successfully, but besides the data it returns the same standard error as has been seen before in MatchMS:
```shell
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-9vos2yi5 because
the default path (/mnt/volume/shared/galaxy/.config/matplotlib) is not a writable directory;
it is highly recommended to set the MPLCONFIGDIR environment variable to a writable
directory, in particular to speed up the import of Matplotlib and to better support
multiprocessing.
Fontconfig error: No writable cache directories
```

This is not critical but may cause the `Combine chunked test results` step of the CI to fail because it caught an error in stderr.

A possible solution could be to set an environment variable `MPLCONFIGDIR` in the wrapper to `/tmp` or `\$_GALAXY_JOB_TMP_DIR`

**Comment by xtrojak** [comment]
@hechth no, I don't think so.
