### ISSUE TITLE
Implement workflow to split library based on metadata

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#330]
Currently the only ways of filtering in matchms is metadata derivation and peak filtering.

It would be good to have the options to split a libraryu based on some metadata keys that are present, like instrument type or ionization method and so on to create a subset of spectra with those properties.

Some keys are (almost) unique, like SMILES, but others describe a group of compounds, like chemical class etc.

First option input format should be MSP and having a single free text input field to identify the field.
This should be implemented by collecting the metadata in an array using the built in matchms [function](https://github.com/matchms/matchms/blob/c70418cc6f1aafbb71b9b2938bde71d4bf886de3/matchms/exporting/metadata_export.py#L94C8-L94C8), then finding the unique values in the specified metadata field (column in the array) and then creating as many lists of spectra as there are unique fields. Then in a for loop all spectra can be sorted into the respective list. The lists can be kept in a dictionary which can be accessed using the unique field identifier.

What we should first try is to use the `matchms metadata export` tool to get all metadata in a table, then `split` the table based on the metadata field which should be used, and then run the `matchms subsetting` tool over the collection. The splitting tool could possibly also have a group for elements where the identifier was not present?

**Comment by xtrojak** [comment]
Maybe this could be implemented as filtering in [matchms](https://matchms.readthedocs.io/en/latest/api/matchms.filtering.html) or postprocessing curation step in [MSMetaEnhancer](https://github.com/RECETOX/MSMetaEnhancer/blob/main/MSMetaEnhancer/libs/Curator.py)?

**Comment by hechth** [comment]
Yeah, it could use the 'require' filters in matchms or be based on those.

Basically we will have to expand the possible fields slowly and systematically.

**Comment by zargham-ahmad** [comment]
@hechth We don't need a separate tool for this. The 2nd option works. We can achieve this by using the `matchms metadata export` tool to get all metadata in a table, then use `Split by group` tool to split the file on unique values from a specified column then use the `cut` tool to cut the required column from the table. This collection can then be used in `matchms subsetting` as a batch job to split the library.

**Comment by hechth** [comment]
AFAIK this should be implemented as a workflow as soon as #429 is fixed?
