### ISSUE TITLE
Deprecate the old recetox-aplcms tools

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#336]

**Comment by xtrojak** [comment]
Deprecated these tools:

- [recetox_aplcms_adjust_time](https://toolshed.g2.bx.psu.edu/repository/browse_repositories_i_own?sort=name&operation=view_or_manage_repository&id=da95f5a0fefb4c9a)
- [recetox_aplcms_extract_features](https://toolshed.g2.bx.psu.edu/repository/browse_repositories_i_own?sort=name&operation=view_or_manage_repository&id=5010d8d8ba339fad)
- [recetox_aplcms_hybrid](https://toolshed.g2.bx.psu.edu/repository/browse_repositories_i_own?sort=name&operation=view_or_manage_repository&id=60e1e9950baf0760)
- [recetox_aplcms_two_step_hybrid](https://toolshed.g2.bx.psu.edu/repository/browse_repositories_i_own?sort=name&operation=view_or_manage_repository&id=d6df73f2d143297a)
- [recetox_aplcms_unsupervised](https://toolshed.g2.bx.psu.edu/repository/browse_repositories_i_own?sort=name&operation=view_or_manage_repository&id=1ec149f7936a1c0d)
