### ISSUE TITLE
recetox-aplcms: change output object names to contain initial input name

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#342]
Currently the objects are called `recetox-aplcms - generate features on data 1` while actually giving the name of data one here (and maybe the number of the dataset in brackets behind it) would be way more convenient.

**Comment by hechth** [comment]
@bgruening the file names and sample names should be as close as possible and ideally not change during processing. So in the first step `remove_noise` we already extract the sample name from the mzml to rely on the filename as little as possible. Getting 100% consistency is quite hard as this would mean really digging into how the dataset identifiers are assigned, so it would introduce a lot of code like writing this extracted sample name to a file and then reading it etc. - so the best we can do is if we have a tool that uses `discover datasets` to then save the files with their sample name as name.

I know that this is not great, but the problem is that the whole `sample name` thing in mass spectrometry is very badly done and inconsistent. Most desktop software removes them from mzml when processing or somehow alters them (OpenMS moves it to a different field in the XML when the file is changed for example) etc. - so it is hard to achieve consistency and to NOT rely on the initial filename (which is what everyone else does in reality anyway). When the file names are then messed with in Galaxy, most tool connections break due to either the file extension being stripped or not or the datasets being renamed etc.

With this approach, we aim to be as little intrusive and changing things as possible.

**Comment by bgruening** [comment]
@hechth have you tried to use consistent collections?

**Comment by hechth** [comment]
@bgruening what do you mean with that? Is that some specific thing or do you mean only using collections?
