### ISSUE TITLE
RAMClustR: enhancements

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#35]
## Description
Add a galaxy tool wrapping RAMClustR.
The tool can be run with XCMS objects or CSV tables as input. These are handled in two different tools for ease of use, but share the same code/container.

### General
- [x] Forward parameters to script from galaxy environment for `xcmsSet` object use
- [x] Implement container to run RAMClustR
- [x] Split tool into two separate parts, one for XCMS object and one for CSV input
- [x] ~~Switch from container to bioconda package once available~~ (continues in https://github.com/RECETOX/galaxytools/issues/114)

### Interface Galaxy -> Tool
- [x] Write wrapper script in tool directory which transforms and handles input - ideally an R script so that the Galaxy tool only calls the function in the R script and we have an interface between the RAMClustR libray and the Galaxy tool

Handle `batch`, `qc` and `order` input parameters by taking a metadata CSV similar to XCMS & WaveICA
- [x] Find proper data type for input - some type of array, text file, numpy array, R array etc
- [x] Transform to R vectors and pass to tool

### Define Experiment Tool
- [x] #216

### CSV Tool
- [x] Implement parameter handling/forwarding using script in tool directory

### Tests:
- [x] Basic test for XCMS based tool
- [x] Basic test for csv based tool once #72  is resolved

### Documentation
- [x] Add upstream/downstream tools
- [x] Add basic background information
- [ ] Describe outputs

**Comment by martenson** [comment]
I made PRs for conda packaging of ramclustr (https://github.com/bioconda/bioconda-recipes/pull/25270) and its last non-packaged dependency (https://github.com/bioconda/bioconda-recipes/pull/25267). When they get merged and built we should switch our wrappers to use them instead of container.

**Comment by hechth** [comment]
The container installs directly from github, so it's also not a bad solution IMHO.

**Comment by martenson** [comment]
If the overhead of maintaining a container can be avoided I'd go for conda. This also gives us very lightweight biocontainers/singularity images for free.

**Comment by hechth** [comment]
> If the overhead of maintaining a container can be avoided I'd go for conda. This also gives us very lightweight biocontainers/singularity images for free.

This is definitely true and also takes away the burden of versioning ;)

**Comment by hechth** [comment]
@martenson I tried switching to using the bioconda package by changing the requirement from
```xml
    <requirements>
        <container type="docker">recetox/ramclustr:1.1.0-recetox0</container>
    </requirements>
```
to
```xml
    <requirements>
        <requirement type="package" version="1.09">r-ramclustr</requirement>
        <requirement type="package" version="3.12.0">bioconductor-xcms</requirement>
    </requirements>
```
but I get the following error: `Conda dependency seemingly installed but failed to build job environment.`

Any ideas?

**Comment by martenson** [comment]
@hechth Where and when are you getting this error? Your local deployment? What environment?

**Comment by hechth** [comment]
I get it on local planemo deployment when trying to run the tool.

**Comment by martenson** [comment]
I can get `conda create env -n ramclustr r-ramclustr` locally to create fine - can you try that?

**Comment by hechth** [comment]
Nope, I get an error using miniconda `conda: error: unrecognized arguments: r-ramclustr` both locally (Windows Laptop using miniconda3) and on abiff machine.

**Comment by martenson** [comment]
oh sorry, typo in env creation, correct is:`conda create -n ramclustr r-ramclustr` (it assumes you have bioconda and conda-forge in your channels)

This works on abiff for me.

**Comment by hechth** [comment]
Same. Can you maybe checkout the PR branch and just run `planemo serve --docker .` in the tools/ramclustr subfolder with the modified requirements part in the xml as given above to see if you can reproduce the error?

**Comment by martenson** [comment]
@hechth There seem to be some package conflicts on dependency installation. I am not sure what Planemo is doing differently. Feel free to continue testing with your container for the time being.

**Comment by hechth** [comment]
> @hechth There seem to be some package conflicts on dependency installation. I am not sure what Planemo is doing differently. Feel free to continue testing with your container for the time being.

Thank you for investigating!

**Comment by martenson** [comment]
The initial implementation has been merged in https://github.com/RECETOX/galaxytools/pull/54

**Comment by hechth** [comment]
Updated subtasks and renamed issue
