### ISSUE TITLE
Create a conversion workflow

### ISSUE THREAD

**Issue by maximskorik** [RECETOX/galaxytools#37]
- [x] Script to export datasets to Sally
- [x] Script to export datasets to library

**Comment by maximskorik** [comment]
Do we let users to choose which library to export to or it's gonna be predefined?

**Comment by martenson** [comment]
@maximskorik the system is going to be automated thus predefined. It will possibly try to mimic the hierarchy on Sally in case the data are used for some applications other than conversion. For the sake of this conversion process there should be no user input assumed. Even the workflow is going to be invoked automatically. Same with the data library import script (this will be a script that calls Galaxy's [API](https://bioblend.readthedocs.io/en/latest/api_docs/galaxy/all.html#module-bioblend.galaxy.libraries), not a tool.
