### ISSUE TITLE
Add EDAM identifiers to matchms suite

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#370]
Input data
- mass spectrum (0943)
- fingerprint (1365)

Format
- msp (missing)
- mgf (3651)
- json (3464)

Operations
- spectral library search (3801) (matchms spectral similarity)
- filtering (3695) (matchms filter)

Outputs
- structure similarity score (0888) (fingerprint similarity)
- distance matrix (2855) (all similarities -> maybe make more precise with spectral similarity score?)

Topics
- Metabolomics
- Compound libraries and screening (3343)

**Comment by xtrojak** [comment]
Consider adding one of Score (1772) / Alignment score or penalty (1394) to the outputs.
