### ISSUE TITLE
Add EDAM identifiers to MSMetaEnhancer

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#371]

**Comment by hechth** [comment]
@xtrojak this can be simplified by just adding the entry on bio.tools and then using the xref. Galaxy will pull the EDAM operations from bio.tools.

**Comment by xtrojak** [comment]
Input Data

- mass spectrometry data (2536)

Format

- msp (TBA)

Operation

- Annotation (0226)

Output

- mass spectrometry data (2536)
