### ISSUE TITLE
Add EDAM identifiers to RIAssigner

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#373]

**Comment by xtrojak** [comment]
Input Data

- Mass spectrum (0943)

Format

- msp (TBA)
- csv (3752)
- tsv (3475)

Operation

- Standardisation and normalisation (3435)

Output

- Mass spectrum (0943)
- Sample annotation (3113)

Topics

- Metabolomics (3172)
- Compound libraries and screening (3343)
- Data submission, annotation, and curation (0219)
