### ISSUE TITLE
Add EDAM identifiers to recetox-xMSannotator

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#383]

**Comment by hechth** [comment]
@xtrojak this was closed in #367 ?

**Comment by xtrojak** [comment]
The xref was added. https://github.com/RECETOX/galaxytools/blob/1ab1a1dabfcebe11720de1411927a7438c1b64c1/tools/recetox_xmsannotator/recetox_xmsannotator_advanced.xml#L9
