### ISSUE TITLE
Run Thermo raw conversion in parallel on collections.

### ISSUE THREAD

**Issue by ljocha** [RECETOX/galaxytools#39]
The current converter
https://github.com/galaxyproteomics/tools-galaxyp/blob/master/tools/ThermoRawFileParser/thermo_converter.xml puts all input files in a folder and invokes a single instance of the converter binary, which processes the files from the folder sequentially. Not optimal for larger batches.

The ultimate option is running a single job per single file, which might not be optimal, but it's worth trying.

If the overhead is too high, it can be done by a job which requests multiple cores, groups the file in several folders, and runs the binary in multiple instances (one on each folder).

**Comment by martenson** [comment]
Side note: our converter pipeline is running it in parallel due to its architecture - it always invokes it on a single dataset.

**Comment by bernt-matthias** [comment]
Please open an issue at the galaxyp repository. I guess this should be changed. With msconvert and the OpenMS FileConverter there are even more options to convert raw files.

@martenson which converter are you using in your pipeline?

**Comment by martenson** [comment]
@bernt-matthias  atm we use `Thermo RAW file converter (Galaxy Version 1.2.3+galaxy0)`, it seems to work ok, but we have a couple of datasets where it just creates empty output collection without creating error. I am going to report that upstream.

**Comment by martenson** [comment]
This has been implemented with https://github.com/galaxyproteomics/tools-galaxyp/pull/560.
