### ISSUE TITLE
matchms conversion: add MS-LIMA MSP style or make RIKEN style compliant with this

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#407]
The format either after converting to RIKEN should be readable by MS-Lima or we implement another option which is based on RIKEN but then makes additional changes.

**Comment by wverastegui** [comment]
#!/bin/sh
filename=$1

sed -E "s,[[:space:]]+, ,g"  $filename > $filename.tmp


grep -rl 'IONMODE' . | xargs sed  '/IONMODE/d' $filename.tmp > $filename.tmp1
grep -rl 'CHARGE' . | xargs sed  '/CHARGE/d' $filename.tmp1 > $filename.tmp2
grep -rl 'COMPOUND_NAME' . | xargs sed  's/COMPOUND_NAME/NAME/g'  $filename.tmp2 > $filename.tmp3

mv $filename.tmp3 $filename
rm -f $filename.tmp1 $filename.tmp2 $filename.tmp3 $filename.tmp
