### ISSUE TITLE
Implement an interactive tool or visualization to view molecular structures in 3D

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#432]
Examples are the ProteinViewer tool / vscode plugin and Avogadro.

**Comment by hechth** [comment]
Find a tool that can be used to visualize molecules.

If there no tool in Galaxy, let's figure out which package or tool would be the best one to wrap in Galaxy.

**Comment by hechth** [comment]
There are extensions for PDB files available - @wverastegui do they also work for SDF? Do they accept PDB files with multiple molecules, so can you just click through the molecules you want to visualize in the interactive visualization module?

**Comment by wverastegui** [comment]
@hechth:
- PV Protein Viewer only shows an unrecognizable draw with "lines" and "points" display modes; with the others, it does not work. 
- NGL Viewer and PV Protein Viewer do not supports SDF. 
- NGL Viewer works only with a single-molecule PDB file. In the case of multiple molecules, it displays only the first molecule.

Visualization tools mentioned are available only in GalaxyEU.

**Comment by hechth** [comment]
NGLViewer seems to be the way to go.
