### ISSUE TITLE
Handle string sanitzing in matchms add key tool

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#481]
Currently, characters like `[` are replaced with `__ob__` etc. which makes it difficult to use the tool. This should be handled, as other tools such as `replace` etc. can actually handle these things.

**Comment by bgruening** [comment]
Its a feature not a bug :)

Galaxy is sanitizing inputs by default. For security. Ideally you design your tools in a way that you do not need those more dangerous inputs. If this is not possible, you can add / tweak the sanitizing with https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-inputs-param-sanitizer
