### ISSUE TITLE
QCxMS: GFN1-xTB is never selected as method

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#511]
We have to verify by running locally how the GFN1-xTB method is selected as this is never the case in the galaxy tool. So far, we have tried `xtb` and `xtb1` as keywords but none of them triggers the correct method.

This has to be checked first locally, then identified which tag needs to be supplied and then the galaxy wrapper updated with this new tag and a accompanying test to avoid this happening again.

**Comment by wverastegui** [comment]
@hechth , @zargham-ahmad . The labels "xtb" for (GFN1-xTB) and "xtb2" for (GFN2-xTB) work as expected when locally run. The incorrect behavior must be on the Galaxy wrapper side.

**Comment by zargham-ahmad** [comment]
@wverastegui did you check if there was a difference in the files generated by the local run and the files generated by Galaxy wrapper?

**Comment by wverastegui** [comment]
I have observed any differences so far.

**Comment by zargham-ahmad** [comment]
the issue was with the leading spaces in the qcxms.in file.
