### ISSUE TITLE
reinstall `export_to_path` tool

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#530]

**Comment by bgruening** [comment]
What is this tool doing? We have an export tool that is flexible in Galaxy already.

**Comment by hechth** [comment]
@bgruening this tool exports files to a network location mounted on worker nodes and the front node - we used to use it to export automatically converted files

**Comment by bgruening** [comment]
Given your locations are configured in the file-sources in Galaxy. You can use Galaxy internal export tool to do that. We are using it that way.

**Comment by hechth** [comment]
They are not, unfortunately I think
