### ISSUE TITLE
apLCMS to RAMClustR: Tool output should be renamed

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#71]
If running the conversion tool the output has exactly the same name in Galaxy history as the input.
Please change it to an appropriate name like "CSV table of <xzy> etc" or so

![image](https://user-images.githubusercontent.com/12066490/102324368-0eb56780-3f82-11eb-9167-f294ee6e6b3c.png)

**Comment by maximskorik** [comment]
Fixed in #73
