### ISSUE TITLE
apLCMS to RAMClustR: Tool fails on actual apLCMS output

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#72]
The tool failst if I try to get the "Aligned Peaks" table or "Peaks" table, see the attached log files.
[2020_12_16_apLCMS_RAMClustR_error_log_aligned_peaks.txt](https://github.com/RECETOX/galaxytools/files/5701368/2020_12_16_apLCMS_RAMClustR_error_log_aligned_peaks.txt)
[2020_12_16_apLCMS_RAMClustR_error_log_peaks.txt](https://github.com/RECETOX/galaxytools/files/5701369/2020_12_16_apLCMS_RAMClustR_error_log_peaks.txt)

@martenson I used an input imported from another history - might that cause this problem?

Update 2020/12/16/10:11
The error was related to an invalid history item.
I replaced it with a valid h5 file, but the tool fails without error message.

**Comment by martenson** [comment]
@hechth That looks like a Galaxy error, the line `    raise FileNotFoundError(f"File {path_or_buf} does not exist")` is very suspicious.

Could you provide me with the dataset or share the history?

**Comment by hechth** [comment]
@martenson Here is the history: https://umsa.cerit-sc.cz/u/6a49c27ceeb84beea728267191c7a8e8/h/aplcms---ramclustr

**Comment by maximskorik** [comment]
I thought there was an issue with the wrapper or the fact that Pandas cannot read '.dat' files (it does as it turned out). I executed the tool in the terminal and when I tried to inspect the csv I got a message from csv-reader stating that it may fail handling that big number of columns. So I thought that may have something to do with failing the execution. I then tried to simply upload the csv output of the converter to Planemo and our Galaxy - both failed.
@martenson is there a chance that galaxy has some sort of limitation on csv size?

**Comment by maximskorik** [comment]
However, if I don't specify the file format, when uploading it uploads

**Comment by maximskorik** [comment]
For example, when executed on data that Helge's sent me it made csv with 131629 columns

**Comment by maximskorik** [comment]
@hechth, I created a PR #74 for the issue. Seems like I was concatenating wrong columns.
 
I was able to run RamClutsR in a container on an output csv as follows:
`> experiment <- defineExperiment(force.skip=TRUE)
> RC1 <- ramclustR(ms = paste0(getwd(), "/apLCMS-test.csv"), featdelim = "_", st = 5, ExpDes=experiment, sampNameCol = 1)`

It returned:
`organizing dataset 
  normalizing dataset 
calculating ramclustR similarity: nblocks =  15 
1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  
 RAMClust feature similarity matrix calculated and stored: 
RAMClust distances converted to distance object 
fastcluster based clustering complete 
dynamicTreeCut based pruning complete 
RAMClust has condensed 9353 features into 1812 spectra 
collapsing feature into spectral signal intensities 
writing msp formatted spectra 
msp file complete `
and msLib file with spectra.

But the RamClutsR in Galaxy fails to execute, so I'm not sure if there's still something to adjust in the converter or I just run the tool with wrong parameters.

**Comment by hechth** [comment]
Can someone confirm this as closed or what the current status is?

**Comment by maximskorik** [comment]
> Can someone confirm this as closed or what the current status is?

It think we can consider the issue resolved. Let's concentrate on the RamClustR wrapper and once it's ready check if both tools function as designed.

**Comment by maximskorik** [comment]
This one seems to be resolved
