### ISSUE TITLE
wrap XCMS

### ISSUE THREAD

**Issue by martenson** [RECETOX/galaxytools#8]
Almost everything seems to be already done. We need to revise whether the existing Galaxy Tools from wf4metabolomics are covering all our use cases.

bioconductor package: https://www.bioconductor.org/packages/release/bioc/html/xcms.html
bioconda package: https://bioconda.github.io/recipes/bioconductor-xcms/README.html#package-bioconductor-xcms
MTS Galaxy Tools suite from W4Metabolomics: https://toolshed.g2.bx.psu.edu/view/lecorguille/suite_xcms/a520686a9627
Custom wf4metabolomics datatypes: https://toolshed.g2.bx.psu.edu/view/lecorguille/rdata_xcms_datatypes/544f6d2329ac
Galaxy tools development repo: https://github.com/workflow4metabolomics/tools-metabolomics/tree/master/tools

**Comment by hechth** [comment]
XCMS from W4F was installed in UMSA Galaxy on 04.11.2020.

**Comment by martenson** [comment]
For now I think we are happy with what is available from W4M. Might reopen later.
