### ISSUE TITLE
Create a tool for batch normalization

### ISSUE THREAD

**Issue by maximskorik** [RECETOX/galaxytools#81]
### Research
- [x] Select an appropriate algorithm for normalization (options: ComBat, WaveICA, NormAE)
-> [WaveICA](https://github.com/dengkuistat/WaveICA) (R package)
- [x]  Identify the proper input format
### Integration
- [x]  Create a Docker image
- [x]  Create a galaxy wrapper

### Further steps
- [x]  Change inputs for the tool once we handle metadata in a workflow
- [x]  Add Galaxy tests
- [ ] Add "Workflow position" section once we have all the up/downstream tools

**Comment by martenson** [comment]
I am going to close this as implemented. The last documentation step is going to be more clear down the road, when we have more pipeline pieces available.
