### ISSUE TITLE
UMSA Galaxy homescreen bug

### ISSUE THREAD

**Issue by maximskorik** [RECETOX/galaxytools#83]
I think I found a small bug at our Galaxy [homescreen](https://umsa.cerit-sc.cz/). When I click the links in red circles it doesn't redirect me. The same thing in Chrome and Firefox.

![home_screen](https://user-images.githubusercontent.com/37554442/107628762-6231f200-6c61-11eb-88af-27b1246a0fef.png)
![error](https://user-images.githubusercontent.com/37554442/107628771-65c57900-6c61-11eb-834b-b3c3add45856.png)
![error_firefox](https://user-images.githubusercontent.com/37554442/107628778-66f6a600-6c61-11eb-9070-a0e77ccd6fdf.png)

**Comment by maximskorik** [comment]
@martenson can you take a look please?

**Comment by martenson** [comment]
@maximskorik fixed, thanks for the report
