### ISSUE TITLE
reintroduce "the golden rules" to xmsannotator

### ISSUE THREAD

**Issue by martenson** [RECETOX/galaxytools#84]
https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-8-105

**Comment by hechth** [comment]
I think this has been adressed @xtracko in #92?

**Comment by martenson** [comment]
Perfect, thanks for reintroducing it @xtracko .

**Comment by martenson** [comment]
We could also consider making this a switchable flag depending on the comparison of results.
