### ISSUE TITLE
apLCMS fails if given larger amounts of data.

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#96]
apLCMS fails if run with large amounts of data (50 samples) - see error from a run on Galaxy below.

```
Error in apLCMS::save_peaks_to_hdf("/mnt/volume/shared/ces-nya/nfs4/home/umsa/object_store_cache/021/dataset_21267.dat",  : 
  object 'x' not found
In addition: Warning messages:
1: In rgl.init(initValue, onlyNULL) : RGL: unable to open X11 display
2: 'rgl.init' failed, running with 'rgl.useNULL = TRUE'. 
Execution halted
```

A different error appears if run on 20 samples - see error from a run on Galaxy  below.
```
**** feature extraction ****
Error in unserialize(node$con) : error reading from connection
Calls: <Anonymous> ... FUN -> recvData -> recvData.SOCKnode -> unserialize
In addition: Warning messages:
1: In rgl.init(initValue, onlyNULL) : RGL: unable to open X11 display
2: 'rgl.init' failed, running with 'rgl.useNULL = TRUE'. 
Execution halted
```

I also ran 20 samples locally, which results in an error in https://github.com/RECETOX/apLCMS/blob/7760a36d600ed07fb4e072f53aff8286218c1e6d/apLCMS/R/adjust.time.R#L69.
The initial file reading and feature detection though runs without problems for a cluster size of 8 and 20 samples.
It then fails due to some error regarding namespace unavailability - might be something local, but still the program proceeds further than on our Galaxy.

```
Starting R session...
ℹ Loading apLCMS
Loading required package: MASS
Loading required package: rgl
This build of rgl does not include OpenGL functions.  Use
 rglwidget() to display results, e.g. via options(rgl.printRglwidget = TRUE).
Loading required package: mzR
Loading required package: Rcpp
Loading required package: splines
Loading required package: doParallel
Loading required package: foreach
Loading required package: iterators
Loading required package: parallel
Loading required package: snow

Attaching package: ‘snow’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, clusterSplit, makeCluster, parApply,
    parCapply, parLapply, parRapply, parSapply, splitIndices,
    stopCluster

Loading required package: gbm
Loaded gbm 2.1.8
Loading required package: e1071
Loading required package: randomForest
randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.
Loading required package: ROCR
Loading required package: ROCS
Loading required package: poibin
load("~/filenames_mzml")

x <- apLCMS::unsupervised(filenames_mzml[1:20], cluster=8)
**** feature extraction ****
 unsupervised.R
**** time correction ****
 unsupervised.R
**** performing time correction ****
 adjust.time.R
m/z tolerance level:  8.9213055807511e-06
 adjust.time.R
time tolerance level: 344.054109620073
 adjust.time.R
the template is sample 20
 adjust.time.R
                to.flip <- which(this.comb[sel, 3] == j)
                temp <- all.ftr.table[to.flip, 2]
                all.ftr.table[to.flip, 2] <- all.ftr.table[to.flip,
                  1]
                all.ftr.table[to.flip, 1] <- temp
                cat(c("sample", j, "using", nrow(all.ftr.table),
                  ","))
                if (j%%3 == 0)
                  cat("\n")
                all.ftr.table <- all.ftr.table[order(all.ftr.table[,
                  2]), ]
                this.dev <- all.ftr.table[, 2]
                aver.time <- all.ftr.table[, 1] - this.dev
                this.feature <- this.feature[order(this.feature[,
                  2], this.feature[, 1]), ]
                this.corrected <- this.old <- this.feature[,
                  2]
                to.correct <- this.old[this.old >= min(this.dev) &
                  this.old <= max(this.dev)]
                this.smooth <- ksmooth(this.dev, aver.time, kernel = "normal",
                  bandwidth = (max(this.dev) - min(this.dev))/5,
                  x.points = to.correct)
                this.corrected[this.old >= min(this.dev) & this.old <=
                  max(this.dev)] <- this.smooth$y + to.correct
                this.corrected[this.old < min(this.dev)] <- this.corrected[this.old <
                  min(this.dev)] + mean(this.smooth$y[this.smooth$x ==
                  min(this.smooth$x)])
                this.corrected[this.old > max(this.dev)] <- this.corrected[this.old >
                  max(this.dev)] + mean(this.smooth$y[this.smooth$x ==
                  max(this.smooth$x)])
                this.feature[, 2] <- this.corrected
                this.feature <- this.feature[order(this.feature[,
                  1], this.feature[, 2]), ]
            }
        }
        this.feature
    }
}

Error in frameTypes(env) :
  non-namespace found within namespace environments
        if (is.null(err)) {
            message <- geterrmessage()
        }
        else {
            attributes(err) <- list()
            message <- err
        }
        body <- list(message = message)
        sendWriteToStdinEvent("", when = "browserPrompt", count = 0)
        session$clearStackTree <- TRUE
        sendStoppedEvent("exception", description = "Stopped on Exception",
            text = message)
        browser()
    }
    else {
        logPrint("showing traceback!!!")
        traceback()
        unregisterEntryFrame()
    }
})()
```

I initially thought that the failure comes because all files are loaded into RAM and then processed, but this is not the case - each core loads a file and then does peak detection, so only the features of all files have to be held in RAM, which is feasible.

**Comment by xtracko** [comment]
It seems that the 2nd traceback points into the original function `adjust.time`, more specifically to a parallel for-cycle https://github.com/RECETOX/apLCMS/blob/7760a36d600ed07fb4e072f53aff8286218c1e6d/apLCMS/R/adjust.time.R#L69-L116. Once, I figured out that the `adjust.time` function needs to have the mzML files ordered in the same order as they were acquired otherwise it fails with some weird error. @hechth, are the files named properly so as they can be sorted by their names in the acquisition order? Could you point me to the dataset you are running it on, please?

**Comment by hechth** [comment]
Yes it points to that parallel for loop.

How do you mean named properly? The names contain increasing numbers in the middle and I think I'm passing the files in that order.

**Comment by xtracko** [comment]
Yes, increasing numbers will do fine as long as they are consistent. I solved it by adding the numbering to the file names (I had 10 testing files). Could you point me to the dataset location which fails so I can debug it?

**Comment by hechth** [comment]
This is not a solution!

I can share the history with you.

**Comment by xtracko** [comment]
> This is not a solution!

It worked because the mistake was in the testing dataset which I downloaded from the internet. So I renamed the files and added a line into apLCMS which sorts the dataset in that order by the filenames. The original documentation on this requirement is non-existent. Hell, by this error I also found that apLCMS requires 3 files at a minimum.

If this hypothesis proves to be the cause of this bug, a more robust solution would be to extend apLCMS to accept a metafile with the proper acquisition ordering of files and their batch assignments.

> 1) Do you know the error which you observed when there is some issue in the ordering?

No, I don't remember it. It was almost a year ago.

> 2) Did you do anything in the code to address this problem?

I've added a [line ](https://github.com/RECETOX/apLCMS/blob/7760a36d600ed07fb4e072f53aff8286218c1e6d/apLCMS/R/unsupervised.R#L176) that sorts the vector if files by their names. The reference top-level function `cdf.to.ftr` did nothing in that regard. 

> 3) If no, why is there no documentation about it?

That would be the mistake of the original authors. We can improve on it by adding a warning into the Galaxy wrapper help or we can add a requirement for the metafile with the proper ordering and batch assignments.

> I shared the history with you.

I found one file `MeOH_shut_down.mzml` in both of these collections which is unsortable by its name into the rest of the collection. Find it's acquisition index, rename it, and please try again. Meantime I will try to run apLCMS without that file.

**Comment by martenson** [comment]
my 2c: Depending on the names of input files for the required input order seems troublesome. Just one example: In our specific use case it could work, because we are symlinking files from Sally, but if you were to use datasets uploaded to Galaxy, you'd have no filename to base this order on.

**Comment by hechth** [comment]
> I found one file MeOH_shut_down.mzml in both of these collections which is unsortable by its name into the rest of the collection. Find it's acquisition index, rename it, and please try again. Meantime I will try to run apLCMS without that file.

The `MeOH_shut_down.mzml` is not contained in the negative test which produces the same error, unfortunately. Also, the files I used locally didn't contain it.

> That would be the mistake of the original authors. We can improve on it by adding a warning into the Galaxy wrapper help or we can add a requirement for the metafile with the proper ordering and batch assignments.

I agree that this would be the best solution.

> No, I don't remember it. It was almost a year ago.

Ok, no worries. I thought asking won't hurt ;). It seems like the error is unrelated to this specific problem, since it also occurs with sorted input lists.

> It worked because the mistake was in the testing dataset which I downloaded from the internet. So I renamed the files and added a line into apLCMS which sorts the dataset in that order by the filenames. The original documentation on this requirement is non-existent. Hell, by this error I also found that apLCMS requires 3 files at a minimum.
>
>If this hypothesis proves to be the cause of this bug, a more robust solution would be to extend apLCMS to accept a metafile with the proper acquisition ordering of files and their batch assignments.

Yeah, we should stick with the metadata I think - it also fits to the other tools. Unfortunately this is likely not our desired solution.

Thanks for hinting to this problem in the original tool!

**Comment by hechth** [comment]
Update: Did a run with 40 samples locally without debugger and it worked out fine.

Remaining tests are a full batch locally and then moving to docker.

**Comment by hechth** [comment]
Update: Running the tool in Docker using 20 samples works also without issues with 8 cores - this is something which already fails in our Galaxy.

**Comment by martenson** [comment]
A analysis of memory consumption has been performed by @ljocha and is available at https://github.com/RECETOX/apLCMS/blob/measure_memory_consumption/test/eval-memory.ipynb. We've also fixed some adjacent bugs wrt wrapper input specification.

The theory is that we know the requirement limits of execution now and this issue can be solved. 

Thanks all
