### ISSUE TITLE
Add workflows to merge metadata with samples data

### ISSUE THREAD

**Issue by maximskorik** [RECETOX/galaxytools#97]
As @martenson pointed out I should've looked for existing tools before developing our own. There is an existing tool to merge metadata and sample data ([Toolshed link](https://toolshed.g2.bx.psu.edu/repository?repository_id=212b6a1d5c144eb0)). And with some changes to a few existing tools (just change separators) it should work just fine in our workflows.

It will throw an error if there are any inconsistencies between data matrix and metadata table though. I don't know how critical it is. Is it possible that some samples will miss metadata?

**Comment by martenson** [comment]
Could you please provide the test data and the expected result, so we can look into what tool can fulfill this?

**Comment by maximskorik** [comment]
I've fixed test input in #94 all the test data are there.

**Comment by maximskorik** [comment]
Also [here's](https://github.com/workflow4metabolomics/tools-metabolomics) GitHub repo for the tool I found.

**Comment by martenson** [comment]
Here are histories that do the merging using common tools:
aplcms:  https://usegalaxy.eu/u/marten/h/aplcms
xcms: https://usegalaxy.eu/u/marten/h/xcms

There is an issue with the xcms version since it rounds the values during the transpose step, losing one digit of precision, but we could maybe adapt that wrapper.

**Comment by hechth** [comment]
So is this exactly the tool we would like to have installed in our Galaxy to merge metadata and sample data tables?

**Comment by martenson** [comment]
@hechth you can see what tools were used in the histories I shared above.

**Comment by hechth** [comment]
Okay so simply the `Join` tool on the two tables does the job if they are both in csv - I see.

**Comment by martenson** [comment]
And if the axes are inverted we can use the `Transpose` tools

**Comment by hechth** [comment]
Then the only problem is that apLCMS loses the names of the samples in the process, which is something I haven't addressed yet, and eventually a tool which collects metadata from a dataset collection.

**Comment by hechth** [comment]
@maximskorik @martenson What was the initial application for this suggestion/tool? And as AFAIK, the workflows posted by martin resolve this problem?

Should we create a small workflow with existing tools that does that, or write down some guideline on how to do this?

I can't seem to find where the actual need for this came from :D

**Comment by martenson** [comment]
@hechth the workflows here implement what https://github.com/RECETOX/galaxytools/pull/94 was intended to do

**Comment by hechth** [comment]
Thanks! I might put them into quick workflows so that we can use them easily again without having to read through the whole conversation here.

**Comment by hechth** [comment]
This tool should also be able to handle the separation again.

**Comment by xtrojak** [comment]
I created workflows for the metadata merging:

- apLCSM: https://umsa.cerit-sc.cz/u/xtrojak/w/merge-metadata-aplcms
- XCMS: https://umsa.cerit-sc.cz/u/xtrojak/w/merge-metadata-xcms

Note that after discussion with @martenson, we discovered that we can't include explicit conversion from `tabular` to `csv` to the workflow the same way it was used in the shared histories.

**Comment by hechth** [comment]
@xtrojak @martenson does that have any implications that it can't be done explicitly?

**Comment by martenson** [comment]
I don't think so.

**Comment by xtrojak** [comment]
Oh sorry I didn't post an answer here, the workflows are published since my previous comment.
Regarding the error, can you provide more details?

**Comment by hechth** [comment]
I think the error was maybe related to not explicitly mentioning certain columns.

Can you acces the information in this dataset here? (https://umsa.cerit-sc.cz/datasets/8a9f81b565b842d8/details)

**Comment by xtrojak** [comment]
Yes, I think you are right, the specification of columns to be used for joining is missing in the workflow inputs. Now they are left empty and it's causing the error.

**Comment by hechth** [comment]
I also checked `keep the header lines` but otherwise nothing else.
